# Configures a node running Kafka, Mosquitto and Redis (including an mqtt-kafka-bridge)
---
classes:
  #- storm::logviewer # Uncomment to enable the logviewer daemon
  - kafka
  - redis::service
  - mosquitto

# Kafka
kafka::broker_id: 0
# kafka::config_map:
#   log.roll.hours: 48
#   log.retention.hours: 48
kafka::kafka_heap_opts: '-Xms2G -Xmx2G -XX:NewSize=256m -XX:MaxNewSize=256m'
kafka::kafka_opts: '-XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintTenuringDistribution'
kafka::zookeeper_connect:
  - 'stormsingle1:2181'