---
classes:
  - supervisor
  - timezone
  - wirbelsturm_yumrepos::confluent
  - wirbelsturm_yumrepos::epel
  - wirbelsturm_yumrepos::miguno
  - wirbelsturm_yumrepos::nginx
  - wirbelsturm_yumrepos::puppetlabs

# Common settings
wirbelsturm_common::ipv6_disable: true
wirbelsturm_common::ipv6_manage: true
wirbelsturm_common::manage_ntp: true
wirbelsturm_common::puppet_package_ensure: '3.3.1-1.el6'
wirbelsturm_common::java_package_name: 'java-1.8.0-openjdk'

# Kafka
kafka::config_map:
  controlled.shutdown.enable: true
  log.roll.hours: 48
  log.retention.hours: 48
kafka::kafka_heap_opts: '-Xms512M -Xmx512M -XX:NewSize=200m -XX:MaxNewSize=200m'
kafka::kafka_opts: '-XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintTenuringDistribution'
kafka::limits_manage: true
kafka::limits_nofile: 65536
kafka::zookeeper_connect:
  - 'zookeeper1:2181'

# # Storm
# storm::package_ensure: '0.9.3-1.miguno'
# storm::zookeeper_servers:
#   - 'zookeeper1'
# storm::nimbus_host: 'nimbus1'
# storm::nimbus_childopts:     '-Xmx256m -Djava.net.preferIPv4Stack=true'
# storm::ui_childopts:         '-Xmx256m -Djava.net.preferIPv4Stack=true'
# storm::supervisor_childopts: '-Xmx256m -Djava.net.preferIPv4Stack=true'
# storm::worker_childopts:     '-Xmx256m -Djava.net.preferIPv4Stack=true'
# storm::supervisor_slots_ports:
#   - 6700
#   - 6701

# Mosquitto
mosquitto::port: '1883'
mosquitto::service_manage: true

# Mongodb
mongodb::port: '27018'
mongodb::verbose: true

# Supervisord
supervisor::logfile_maxbytes: '20MB'
supervisor::logfile_backups: 5
supervisor::autoupgrade: true

# Timezone
timezone::timezone: 'UTC'

# ZooKeeper
# If you want to use a quorum (of usually 3 or 5 ZooKeeper servers), use a configuration similar as the following.
# Make sure to set 'zookeeper::myid' appropriately for the machines in the quorum (myid must match 'server.X').
#zookeeper::quorum:
#  - 'server.1=zookeeper1:2888:3888'
#  - 'server.2=zookeeper2:2888:3888'
#  - 'server.3=zookeeper3:2888:3888'
